//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.09 at 04:48:29 PM CET 
//


package jaxbProject.galaxy.entityMultiple;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="InvoiceDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="InvoiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InvoiceCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ExchangeRate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="SendEInv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountingSupplierParty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NIPT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PostalAddress">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PartyTaxScheme">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TaxScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountingCustomerParty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NIPT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Customer_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PostalAddress">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PartyTaxScheme">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TaxScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Invoice_Line" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LineNum" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="LineQuantity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="Line_Net_Value_after_discount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="Line_Discount_Value" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="Tax_Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="TaxInclusiveAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="Item">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ClassifiedTaxCategory">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Vat_Percent" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="Vat_Scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Price">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PriceAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="BaseQuantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PaymentTerms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PaymentPaymentTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceHeader",
    "accountingSupplierParty",
    "accountingCustomerParty",
    "invoiceLine",
    "paymentTerms"
})
@XmlRootElement(name = "Invoice")
public class Invoice {

    @XmlElement(name = "InvoiceHeader", required = true)
    protected Invoice.InvoiceHeader invoiceHeader;
    @XmlElement(name = "AccountingSupplierParty", required = true)
    protected Invoice.AccountingSupplierParty accountingSupplierParty;
    @XmlElement(name = "AccountingCustomerParty", required = true)
    protected Invoice.AccountingCustomerParty accountingCustomerParty;
    @XmlElement(name = "Invoice_Line")
    protected List<Invoice.InvoiceLine> invoiceLine;
    @XmlElement(name = "PaymentTerms", required = true)
    protected Invoice.PaymentTerms paymentTerms;

    /**
     * Gets the value of the invoiceHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.InvoiceHeader }
     *     
     */
    public Invoice.InvoiceHeader getInvoiceHeader() {
        return invoiceHeader;
    }

    /**
     * Sets the value of the invoiceHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.InvoiceHeader }
     *     
     */
    public void setInvoiceHeader(Invoice.InvoiceHeader value) {
        this.invoiceHeader = value;
    }

    /**
     * Gets the value of the accountingSupplierParty property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.AccountingSupplierParty }
     *     
     */
    public Invoice.AccountingSupplierParty getAccountingSupplierParty() {
        return accountingSupplierParty;
    }

    /**
     * Sets the value of the accountingSupplierParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.AccountingSupplierParty }
     *     
     */
    public void setAccountingSupplierParty(Invoice.AccountingSupplierParty value) {
        this.accountingSupplierParty = value;
    }

    /**
     * Gets the value of the accountingCustomerParty property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.AccountingCustomerParty }
     *     
     */
    public Invoice.AccountingCustomerParty getAccountingCustomerParty() {
        return accountingCustomerParty;
    }

    /**
     * Sets the value of the accountingCustomerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.AccountingCustomerParty }
     *     
     */
    public void setAccountingCustomerParty(Invoice.AccountingCustomerParty value) {
        this.accountingCustomerParty = value;
    }

    /**
     * Gets the value of the invoiceLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Invoice.InvoiceLine }
     * 
     * 
     */
    public List<Invoice.InvoiceLine> getInvoiceLine() {
        if (invoiceLine == null) {
            invoiceLine = new ArrayList<Invoice.InvoiceLine>();
        }
        return this.invoiceLine;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.PaymentTerms }
     *     
     */
    public Invoice.PaymentTerms getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.PaymentTerms }
     *     
     */
    public void setPaymentTerms(Invoice.PaymentTerms value) {
        this.paymentTerms = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NIPT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Customer_Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PostalAddress">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PartyTaxScheme">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TaxScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "nipt",
        "customerDescription",
        "postalAddress",
        "partyTaxScheme"
    })
    public static class AccountingCustomerParty {

        @XmlElement(name = "ID")
        protected short id;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "NIPT", required = true)
        protected String nipt;
        @XmlElement(name = "Customer_Description", required = true)
        protected String customerDescription;
        @XmlElement(name = "PostalAddress", required = true)
        protected Invoice.AccountingCustomerParty.PostalAddress postalAddress;
        @XmlElement(name = "PartyTaxScheme", required = true)
        protected Invoice.AccountingCustomerParty.PartyTaxScheme partyTaxScheme;

        /**
         * Gets the value of the id property.
         * 
         */
        public short getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setID(short value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the nipt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNIPT() {
            return nipt;
        }

        /**
         * Sets the value of the nipt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNIPT(String value) {
            this.nipt = value;
        }

        /**
         * Gets the value of the customerDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerDescription() {
            return customerDescription;
        }

        /**
         * Sets the value of the customerDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerDescription(String value) {
            this.customerDescription = value;
        }

        /**
         * Gets the value of the postalAddress property.
         * 
         * @return
         *     possible object is
         *     {@link Invoice.AccountingCustomerParty.PostalAddress }
         *     
         */
        public Invoice.AccountingCustomerParty.PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link Invoice.AccountingCustomerParty.PostalAddress }
         *     
         */
        public void setPostalAddress(Invoice.AccountingCustomerParty.PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the partyTaxScheme property.
         * 
         * @return
         *     possible object is
         *     {@link Invoice.AccountingCustomerParty.PartyTaxScheme }
         *     
         */
        public Invoice.AccountingCustomerParty.PartyTaxScheme getPartyTaxScheme() {
            return partyTaxScheme;
        }

        /**
         * Sets the value of the partyTaxScheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link Invoice.AccountingCustomerParty.PartyTaxScheme }
         *     
         */
        public void setPartyTaxScheme(Invoice.AccountingCustomerParty.PartyTaxScheme value) {
            this.partyTaxScheme = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TaxScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxScheme"
        })
        public static class PartyTaxScheme {

            @XmlElement(name = "TaxScheme", required = true)
            protected String taxScheme;

            /**
             * Gets the value of the taxScheme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxScheme() {
                return taxScheme;
            }

            /**
             * Sets the value of the taxScheme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxScheme(String value) {
                this.taxScheme = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "countryID",
            "countryName"
        })
        public static class PostalAddress {

            @XmlElement(name = "CountryID", required = true)
            protected String countryID;
            @XmlElement(name = "CountryName", required = true)
            protected String countryName;

            /**
             * Gets the value of the countryID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryID() {
                return countryID;
            }

            /**
             * Sets the value of the countryID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryID(String value) {
                this.countryID = value;
            }

            /**
             * Gets the value of the countryName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryName() {
                return countryName;
            }

            /**
             * Sets the value of the countryName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryName(String value) {
                this.countryName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NIPT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PostalAddress">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PartyTaxScheme">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TaxScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "nipt",
        "postalAddress",
        "partyTaxScheme"
    })
    public static class AccountingSupplierParty {

        @XmlElement(name = "ID")
        protected byte id;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "NIPT", required = true)
        protected String nipt;
        @XmlElement(name = "PostalAddress", required = true)
        protected Invoice.AccountingSupplierParty.PostalAddress postalAddress;
        @XmlElement(name = "PartyTaxScheme", required = true)
        protected Invoice.AccountingSupplierParty.PartyTaxScheme partyTaxScheme;

        /**
         * Gets the value of the id property.
         * 
         */
        public byte getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setID(byte value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the nipt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNIPT() {
            return nipt;
        }

        /**
         * Sets the value of the nipt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNIPT(String value) {
            this.nipt = value;
        }

        /**
         * Gets the value of the postalAddress property.
         * 
         * @return
         *     possible object is
         *     {@link Invoice.AccountingSupplierParty.PostalAddress }
         *     
         */
        public Invoice.AccountingSupplierParty.PostalAddress getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link Invoice.AccountingSupplierParty.PostalAddress }
         *     
         */
        public void setPostalAddress(Invoice.AccountingSupplierParty.PostalAddress value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the partyTaxScheme property.
         * 
         * @return
         *     possible object is
         *     {@link Invoice.AccountingSupplierParty.PartyTaxScheme }
         *     
         */
        public Invoice.AccountingSupplierParty.PartyTaxScheme getPartyTaxScheme() {
            return partyTaxScheme;
        }

        /**
         * Sets the value of the partyTaxScheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link Invoice.AccountingSupplierParty.PartyTaxScheme }
         *     
         */
        public void setPartyTaxScheme(Invoice.AccountingSupplierParty.PartyTaxScheme value) {
            this.partyTaxScheme = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TaxScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxScheme"
        })
        public static class PartyTaxScheme {

            @XmlElement(name = "TaxScheme", required = true)
            protected String taxScheme;

            /**
             * Gets the value of the taxScheme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxScheme() {
                return taxScheme;
            }

            /**
             * Sets the value of the taxScheme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxScheme(String value) {
                this.taxScheme = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CountryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "streetName",
            "cityName",
            "countryID",
            "countryName"
        })
        public static class PostalAddress {

            @XmlElement(name = "StreetName", required = true)
            protected String streetName;
            @XmlElement(name = "CityName", required = true)
            protected String cityName;
            @XmlElement(name = "CountryID", required = true)
            protected String countryID;
            @XmlElement(name = "CountryName", required = true)
            protected String countryName;

            /**
             * Gets the value of the streetName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreetName() {
                return streetName;
            }

            /**
             * Sets the value of the streetName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreetName(String value) {
                this.streetName = value;
            }

            /**
             * Gets the value of the cityName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCityName() {
                return cityName;
            }

            /**
             * Sets the value of the cityName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCityName(String value) {
                this.cityName = value;
            }

            /**
             * Gets the value of the countryID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryID() {
                return countryID;
            }

            /**
             * Sets the value of the countryID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryID(String value) {
                this.countryID = value;
            }

            /**
             * Gets the value of the countryName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryName() {
                return countryName;
            }

            /**
             * Sets the value of the countryName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryName(String value) {
                this.countryName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="InvoiceDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="InvoiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InvoiceCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ExchangeRate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="SendEInv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "invoiceNumber",
        "invoiceDate",
        "invoiceType",
        "invoiceCurrencyCode",
        "exchangeRate",
        "sendEInv"
    })
    public static class InvoiceHeader {

        @XmlElement(name = "InvoiceNumber")
        protected int invoiceNumber;
        @XmlElement(name = "InvoiceDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar invoiceDate;
        @XmlElement(name = "InvoiceType", required = true)
        protected String invoiceType;
        @XmlElement(name = "InvoiceCurrencyCode", required = true)
        protected String invoiceCurrencyCode;
        @XmlElement(name = "ExchangeRate")
        protected float exchangeRate;
        @XmlElement(name = "SendEInv", required = true)
        protected String sendEInv;

        /**
         * Gets the value of the invoiceNumber property.
         * 
         */
        public int getInvoiceNumber() {
            return invoiceNumber;
        }

        /**
         * Sets the value of the invoiceNumber property.
         * 
         */
        public void setInvoiceNumber(int value) {
            this.invoiceNumber = value;
        }

        /**
         * Gets the value of the invoiceDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getInvoiceDate() {
            return invoiceDate;
        }

        /**
         * Sets the value of the invoiceDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setInvoiceDate(XMLGregorianCalendar value) {
            this.invoiceDate = value;
        }

        /**
         * Gets the value of the invoiceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvoiceType() {
            return invoiceType;
        }

        /**
         * Sets the value of the invoiceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvoiceType(String value) {
            this.invoiceType = value;
        }

        /**
         * Gets the value of the invoiceCurrencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvoiceCurrencyCode() {
            return invoiceCurrencyCode;
        }

        /**
         * Sets the value of the invoiceCurrencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvoiceCurrencyCode(String value) {
            this.invoiceCurrencyCode = value;
        }

        /**
         * Gets the value of the exchangeRate property.
         * 
         */
        public float getExchangeRate() {
            return exchangeRate;
        }

        /**
         * Sets the value of the exchangeRate property.
         * 
         */
        public void setExchangeRate(float value) {
            this.exchangeRate = value;
        }

        /**
         * Gets the value of the sendEInv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSendEInv() {
            return sendEInv;
        }

        /**
         * Sets the value of the sendEInv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSendEInv(String value) {
            this.sendEInv = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LineNum" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="LineQuantity" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="Line_Net_Value_after_discount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="Line_Discount_Value" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="Tax_Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="TaxInclusiveAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="Item">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ClassifiedTaxCategory">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Vat_Percent" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="Vat_Scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Price">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PriceAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="BaseQuantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lineNum",
        "lineQuantity",
        "lineNetValueAfterDiscount",
        "lineDiscountValue",
        "taxAmount",
        "taxInclusiveAmount",
        "item",
        "price"
    })
    public static class InvoiceLine {

        @XmlElement(name = "LineNum")
        protected byte lineNum;
        @XmlElement(name = "LineQuantity")
        protected float lineQuantity;
        @XmlElement(name = "Line_Net_Value_after_discount")
        protected float lineNetValueAfterDiscount;
        @XmlElement(name = "Line_Discount_Value")
        protected float lineDiscountValue;
        @XmlElement(name = "Tax_Amount")
        protected float taxAmount;
        @XmlElement(name = "TaxInclusiveAmount")
        protected float taxInclusiveAmount;
        @XmlElement(name = "Item", required = true)
        protected Invoice.InvoiceLine.Item item;
        @XmlElement(name = "Price", required = true)
        protected Invoice.InvoiceLine.Price price;

        /**
         * Gets the value of the lineNum property.
         * 
         */
        public byte getLineNum() {
            return lineNum;
        }

        /**
         * Sets the value of the lineNum property.
         * 
         */
        public void setLineNum(byte value) {
            this.lineNum = value;
        }

        /**
         * Gets the value of the lineQuantity property.
         * 
         */
        public float getLineQuantity() {
            return lineQuantity;
        }

        /**
         * Sets the value of the lineQuantity property.
         * 
         */
        public void setLineQuantity(float value) {
            this.lineQuantity = value;
        }

        /**
         * Gets the value of the lineNetValueAfterDiscount property.
         * 
         */
        public float getLineNetValueAfterDiscount() {
            return lineNetValueAfterDiscount;
        }

        /**
         * Sets the value of the lineNetValueAfterDiscount property.
         * 
         */
        public void setLineNetValueAfterDiscount(float value) {
            this.lineNetValueAfterDiscount = value;
        }

        /**
         * Gets the value of the lineDiscountValue property.
         * 
         */
        public float getLineDiscountValue() {
            return lineDiscountValue;
        }

        /**
         * Sets the value of the lineDiscountValue property.
         * 
         */
        public void setLineDiscountValue(float value) {
            this.lineDiscountValue = value;
        }

        /**
         * Gets the value of the taxAmount property.
         * 
         */
        public float getTaxAmount() {
            return taxAmount;
        }

        /**
         * Sets the value of the taxAmount property.
         * 
         */
        public void setTaxAmount(float value) {
            this.taxAmount = value;
        }

        /**
         * Gets the value of the taxInclusiveAmount property.
         * 
         */
        public float getTaxInclusiveAmount() {
            return taxInclusiveAmount;
        }

        /**
         * Sets the value of the taxInclusiveAmount property.
         * 
         */
        public void setTaxInclusiveAmount(float value) {
            this.taxInclusiveAmount = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link Invoice.InvoiceLine.Item }
         *     
         */
        public Invoice.InvoiceLine.Item getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link Invoice.InvoiceLine.Item }
         *     
         */
        public void setItem(Invoice.InvoiceLine.Item value) {
            this.item = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link Invoice.InvoiceLine.Price }
         *     
         */
        public Invoice.InvoiceLine.Price getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link Invoice.InvoiceLine.Price }
         *     
         */
        public void setPrice(Invoice.InvoiceLine.Price value) {
            this.price = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ClassifiedTaxCategory">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Vat_Percent" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="Vat_Scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "description",
            "notes",
            "classifiedTaxCategory"
        })
        public static class Item {

            @XmlElement(name = "Code", required = true)
            protected String code;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "Notes", required = true)
            protected String notes;
            @XmlElement(name = "ClassifiedTaxCategory", required = true)
            protected Invoice.InvoiceLine.Item.ClassifiedTaxCategory classifiedTaxCategory;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the notes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNotes() {
                return notes;
            }

            /**
             * Sets the value of the notes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNotes(String value) {
                this.notes = value;
            }

            /**
             * Gets the value of the classifiedTaxCategory property.
             * 
             * @return
             *     possible object is
             *     {@link Invoice.InvoiceLine.Item.ClassifiedTaxCategory }
             *     
             */
            public Invoice.InvoiceLine.Item.ClassifiedTaxCategory getClassifiedTaxCategory() {
                return classifiedTaxCategory;
            }

            /**
             * Sets the value of the classifiedTaxCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link Invoice.InvoiceLine.Item.ClassifiedTaxCategory }
             *     
             */
            public void setClassifiedTaxCategory(Invoice.InvoiceLine.Item.ClassifiedTaxCategory value) {
                this.classifiedTaxCategory = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Vat_Percent" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="Vat_Scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "vatPercent",
                "vatScheme"
            })
            public static class ClassifiedTaxCategory {

                @XmlElement(name = "Vat_Percent")
                protected float vatPercent;
                @XmlElement(name = "Vat_Scheme", required = true)
                protected String vatScheme;

                /**
                 * Gets the value of the vatPercent property.
                 * 
                 */
                public float getVatPercent() {
                    return vatPercent;
                }

                /**
                 * Sets the value of the vatPercent property.
                 * 
                 */
                public void setVatPercent(float value) {
                    this.vatPercent = value;
                }

                /**
                 * Gets the value of the vatScheme property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVatScheme() {
                    return vatScheme;
                }

                /**
                 * Sets the value of the vatScheme property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVatScheme(String value) {
                    this.vatScheme = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PriceAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="BaseQuantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priceAmount",
            "baseQuantity"
        })
        public static class Price {

            @XmlElement(name = "PriceAmount")
            protected float priceAmount;
            @XmlElement(name = "BaseQuantity")
            protected byte baseQuantity;

            /**
             * Gets the value of the priceAmount property.
             * 
             */
            public float getPriceAmount() {
                return priceAmount;
            }

            /**
             * Sets the value of the priceAmount property.
             * 
             */
            public void setPriceAmount(float value) {
                this.priceAmount = value;
            }

            /**
             * Gets the value of the baseQuantity property.
             * 
             */
            public byte getBaseQuantity() {
                return baseQuantity;
            }

            /**
             * Sets the value of the baseQuantity property.
             * 
             */
            public void setBaseQuantity(byte value) {
                this.baseQuantity = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PaymentPaymentTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentPaymentTerm"
    })
    public static class PaymentTerms {

        @XmlElement(name = "PaymentPaymentTerm", required = true)
        protected String paymentPaymentTerm;

        /**
         * Gets the value of the paymentPaymentTerm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentPaymentTerm() {
            return paymentPaymentTerm;
        }

        /**
         * Sets the value of the paymentPaymentTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentPaymentTerm(String value) {
            this.paymentPaymentTerm = value;
        }

    }

}
