//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 03:04:57 PM CET 
//


package jaxbProject.galaxy;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxbProject.galaxy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxbProject.galaxy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceLine }
     * 
     */
    public Invoice.InvoiceLine createInvoiceInvoiceLine() {
        return new Invoice.InvoiceLine();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceLine.Item }
     * 
     */
    public Invoice.InvoiceLine.Item createInvoiceInvoiceLineItem() {
        return new Invoice.InvoiceLine.Item();
    }

    /**
     * Create an instance of {@link Invoice.AccountingCustomerParty }
     * 
     */
    public Invoice.AccountingCustomerParty createInvoiceAccountingCustomerParty() {
        return new Invoice.AccountingCustomerParty();
    }

    /**
     * Create an instance of {@link Invoice.AccountingSupplierParty }
     * 
     */
    public Invoice.AccountingSupplierParty createInvoiceAccountingSupplierParty() {
        return new Invoice.AccountingSupplierParty();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceHeader }
     * 
     */
    public Invoice.InvoiceHeader createInvoiceInvoiceHeader() {
        return new Invoice.InvoiceHeader();
    }

    /**
     * Create an instance of {@link Invoice.PaymentTerms }
     * 
     */
    public Invoice.PaymentTerms createInvoicePaymentTerms() {
        return new Invoice.PaymentTerms();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceLine.Price }
     * 
     */
    public Invoice.InvoiceLine.Price createInvoiceInvoiceLinePrice() {
        return new Invoice.InvoiceLine.Price();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceLine.Item.ClassifiedTaxCategory }
     * 
     */
    public Invoice.InvoiceLine.Item.ClassifiedTaxCategory createInvoiceInvoiceLineItemClassifiedTaxCategory() {
        return new Invoice.InvoiceLine.Item.ClassifiedTaxCategory();
    }

    /**
     * Create an instance of {@link Invoice.AccountingCustomerParty.PostalAddress }
     * 
     */
    public Invoice.AccountingCustomerParty.PostalAddress createInvoiceAccountingCustomerPartyPostalAddress() {
        return new Invoice.AccountingCustomerParty.PostalAddress();
    }

    /**
     * Create an instance of {@link Invoice.AccountingCustomerParty.PartyTaxScheme }
     * 
     */
    public Invoice.AccountingCustomerParty.PartyTaxScheme createInvoiceAccountingCustomerPartyPartyTaxScheme() {
        return new Invoice.AccountingCustomerParty.PartyTaxScheme();
    }

    /**
     * Create an instance of {@link Invoice.AccountingSupplierParty.PostalAddress }
     * 
     */
    public Invoice.AccountingSupplierParty.PostalAddress createInvoiceAccountingSupplierPartyPostalAddress() {
        return new Invoice.AccountingSupplierParty.PostalAddress();
    }

    /**
     * Create an instance of {@link Invoice.AccountingSupplierParty.PartyTaxScheme }
     * 
     */
    public Invoice.AccountingSupplierParty.PartyTaxScheme createInvoiceAccountingSupplierPartyPartyTaxScheme() {
        return new Invoice.AccountingSupplierParty.PartyTaxScheme();
    }

    /**
     * Create an instance of {@link Invoice.AccountingSupplierParty.Contact }
     * 
     */
    public Invoice.AccountingSupplierParty.Contact createInvoiceAccountingSupplierPartyContact() {
        return new Invoice.AccountingSupplierParty.Contact();
    }

}
